config/routes.rb
Rails.application.routes.draw do

  get 'calendars/index'
  post 'calendars/index'

  get 'welcome/login'
  post 'welcome/login_attempt', as: 'login_attempt'
  get '/logout', to: 'welcome#logout'
  post '/logout', to: 'welcome#logout'

  resources :users
  resources :calendars do
    resources :exercises
  end

  root 'welcome#login'

end

app/models/calendar.rb
class Calendar < ActiveRecord::Base
  has_many :exercises

  def self.days_in_month(month, year)
    case month
      when 1, 3, 5, 7, 8, 10, 12
      	return 31
      when 4, 6, 9, 11
      	return 30
      when 2
      	if Calendar.leap_year(year) == 1
      		return 29
      	else
      		return 28
      	end
    end
  end

  def self.leap_year(year)
    if year % 400 == 0
      return 1
    elseif year % 100 == 0
      return 0
    elseif year % 4 == 0
      return 1
    else
      return 0
    end
  end
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :calendar
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :presence => true, :uniqueness => true, :length => { :in => 4..20 }
	validates :password, :confirmation => true

	def self.authenticate(username="", login_password="")
      user = User.find_by_username(username)

      if user && user.match_password(user.password, login_password)
      	return user
      else
      	return false
      end
	end

	def match_password(password, login_password)
      if password == login_password
		return true
	  else
		false
	  end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected 
  def authenticate_user
    if session[:user_id]
       # set current user object to @current_user object variable
      @current_user = User.find session[:user_id] 
      return true	
    else
      redirect_to(:controller => 'welcome', :action => 'login')
      return false
    end
  end
  def save_login_state
    if session[:user_id]
      redirect_to(:controller => 'calendars', :action => 'index')
      return false
    else
      return true
    end
  end
end

app/controllers/calendars_controller.rb
require 'date'

class CalendarsController < ApplicationController
  before_filter :authenticate_user

  attr_accessor :day
  attr_accessor :week
  attr_accessor :started

  def index
  	@started = 0
  	@week = 1
  	if (params[:year].to_i > 0)
  		@time = Date.new(params[:year].to_i, params[:month].to_i, 1)
  		if (params[:direction] == 'prev')
  			@time = @time - 1.month
  		elsif (params[:direction] == 'next')
  			@time = @time + 1.month
  		end
  	else
  		@time = DateTime.now
  	end

  	@calendars = Calendar.where(user: session[:user_id].to_s).where("strftime('%m', date)+0 = ?", @time.month).where("strftime('%Y', date)+0 = ?", @time.year)
  	@exes = []
  	@calendars.each do |calendar|
  		@exes[calendar.date.day] = calendar
  	end

  	@days_now = Calendar.days_in_month(@time.month, @time.year)
  	@day = Date.new(@time.year, @time.month, 1).wday
  	if @day == 0
  		@day = 7
  	end
  end

  def show
  	@calendar = Calendar.find(params[:id])
  end

  def new
  	@day = params[:day].to_i
  	@month = params[:month].to_i
  	@year = params[:year].to_i
  	@date = Date.new(@year, @month, @day)

  	@calendar = Calendar.new
  end

  def edit
  	@calendar = Calendar.find(params[:id])
  end

  def update
  	@calendar = Calendar.find(params[:id])

  	if @calendar.update(calendar_params)
  		redirect_to @calendar
  	else
  		render 'edit'
  	end
  end

  def create
  	@calendar = Calendar.new(calendar_params)
	@time = @calendar.date

  	if @calendar.save
  		redirect_to calendars_path(:month => @time.month, :year => @time.year)
  	else
  		render 'new'
  	end
  end

  def destroy
  	@calendar = Calendar.find(params[:id])
  	@calendar.destroy
  	redirect_to calendars_path
  end

  private
	  def calendar_params
	  	params.require(:calendar).permit(:date, :user, :desc)
	  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController

	def create
		@calendar = Calendar.find(params[:calendar_id])
		@exercise = @calendar.exercises.create(exercise_params)
		redirect_to calendar_path(@calendar)
	end

	def edit
		@calendar = Calendar.find(params[:calendar_id])
		@exercise = @calendar.exercises.find(params[:id])
	end

	def update
		@calendar = Calendar.find(params[:calendar_id])
		@exercise = @calendar.exercises.find(params[:id])

		if @exercise.update(exercise_params)
			redirect_to @calendar
		else
			render 'edit'
		end
	end

	def destroy
		@calendar = Calendar.find(params[:calendar_id])
		@exercise = @calendar.exercises.find(params[:id])
		@exercise.destroy
		redirect_to calendar_path(@calendar)
	end

	private
		def exercise_params
			params.require(:exercise).permit(:title, :body, :url)
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)

		if @user.save
          redirect_to '/'
        else
          render 'new'
        end
	end

	private
	  def user_params
	    params.require(:user).permit(:username, :password, :password_confirmation)
	  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :save_login_state, :only => [:login, :login_attempt]

  def index
  end

  def login
  end

  def login_attempt
  	authorized_user = User.authenticate(params[:username], params[:login_password])
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = nil
      redirect_to :controller => 'calendars', :action => 'index'
    else
      flash[:notice] = "Invalid Username or Password"
      flash[:color] = "invalid"
      render "login"
    end
  end

  def logout
  	session[:user_id] = nil
    flash[:notice] = nil
    redirect_to '/'
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/calendars/_addexercise.html.erb
<div class="addexercise">
	<%= form_for([@calendar, @calendar.exercises.build]) do |f| %>
		<div class="form_row">
			<div class="label"><%= f.label :title %></div>
			<%= f.text_field :title %>
		</div>
		<div class="form_row">
			<div class="label"><%= f.label :body %></div>
			<%= f.text_area :body %>
		</div>
		<div class="form_row">
			<div class="label"><%= f.label :url %></div>
			<%= f.text_field :url %>
		</div>
		
		<div class="form_row">
			<%= f.submit 'Add new exercise', :class => 'button' %>
		</div>
	<% end %>
</div>

app/views/calendars/_calendar.html.erb
<div class="calendar">
	<div class="selector">
		<%= button_to "Previous", {:action => 'index', :month => @time.month, :year => @time.year, :direction => 'prev'}, {class: 'item'} %>

		<p class="item"><%=@time.strftime("%B")%>, <%=@time.year%></p>
		
		<%= button_to "Next", {:action => 'index', :month => @time.month, :year => @time.year, :direction => 'next'}, {class: 'item'} %>
	</div>
      <div class="week">
        <div class="day-header">Mon</div>
        <div class="day-header">Tue</div>
        <div class="day-header">Wed</div>
        <div class="day-header">Thu</div>
        <div class="day-header">Fri</div>
        <div class="day-header">Sat</div>
        <div class="day-header">Sun</div>
      </div>
	<% @days_now.times do |n| %>
	<% if @day == 1 || @started == 0 %>
	  <div class="week">
	  <% if @day != 1 %>
	  	<% 1.upto(@day -1) do %>
	  	<div class="day"></div>
	  	<% end %>
	  <% end %>
	<% @started = 1 %>
	<% end %>

    	<% if @exes[n+1] == nil %>
    		<div class="day no-exes">
    			<%= link_to n+1, new_calendar_path(:day => n+1, :month => @time.month, :year => @time.year) %>
    		</div>
    	<% else %>
    		<div class="day with-exes">
    			<%= link_to n+1, calendar_path(@exes[n+1]) %>
    			<p><%= @exes[n+1].desc %></p>
    		</div>
    	<% end %>


	<% if @day == 7 || n+1 == @days_now %>
	  <% if n+1 == @days_now && @day != 7 %>
	  <% @day.upto(6) do %>
	    <div class="day"></div>
	  <% end %>
	  <% end %>
	  </div>
	<% end %>
	<% if @day == 7
	  		@day = 1
	  		@week += 1
	  	else
	  		@day += 1
	  	end %>
	<% end %>

</div>

app/views/calendars/_logout.html.erb
<%= button_to "Log out", {:action => 'logout', :controller => 'welcome'}, {:class => 'logout-button'} %>

app/views/calendars/edit.html.erb
<h2>Edit exercise day for <%= @calendar.date.strftime("%B") %> <%= @calendar.date.day %>, <%= @calendar.date.year %></h2>

<% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@calendar.errors.count, "error") %> prohibited
        this day from being added:
      </h2>
      <ul>
        <% @calendar.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="addexerciseday">
  <%= form_for @calendar do |f| %>
    <%= f.hidden_field :date %>
    <%= f.hidden_field :user, :value => session[:user_id] %>

    <div class="form_row">
      <div class="label"><%= f.label :description %></div>
      <%= f.text_field :desc %>
    </div>

    <div class="form_row">
      <%= f.submit :Add, :class => 'button' %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', @calendar %>

app/views/calendars/index.html.erb
<%= render partial: 'logout' %>

<h1>Your training calendar</h1>

<%= render partial: 'calendar' %>

app/views/calendars/new.html.erb
<h2>Add exercise day for <%= @month %>/<%= @day %>/<%= @year %></h2>

<% if @calendar.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@calendar.errors.count, "error") %> prohibited
        this day from being added:
      </h2>
      <ul>
        <% @calendar.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="addexerciseday">
  <%= form_for @calendar do |f| %>
    <%= f.hidden_field :date, :value => @date %>
    <%= f.hidden_field :user, :value => session[:user_id] %>

    <div class="form_row">
      <div class="label"><%= f.label :description %></div>
      <%= f.text_field :desc %>
    </div>

    <div class="form_row">
      <%= f.submit :Add, :class => 'button' %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', calendars_path %>

app/views/calendars/prev_month.html.erb
	<h1>Calendar#prev_month</h1>
<p>Find me in app/views/calendar/index.html.erb</p>

<%= render partial: 'calendar' %>

app/views/calendars/show.html.erb
<%= render partial: 'logout' %>

<div class="day-top">
	<h1><%= @calendar.date.strftime("%B") %> <%= @calendar.date.day %>, <%= @calendar.date.year %></h1>
	<%= link_to 'Edit', edit_calendar_path %>
	<%= link_to 'Destroy', @calendar, method: :delete, data: { confirm: 'Are you sure?' } %>
</div>
<p><strong>Day description:</strong> <%= @calendar.desc %></p>

<h2>Exercises</h2>
<% @calendar.exercises.each do |exercise| %>
	<div class="single-exercise">
		<div class="header-row">
			<h3><%= exercise.title %></h3>
			<%= link_to 'Destroy exercise', [exercise.calendar, exercise],
	               method: :delete,
	               data: { confirm: 'Are you sure?' } %>
	    	<%= link_to 'Edit exercise',#, [exercise.calendar, exercise],
	    		   edit_calendar_exercise_path(:calendar_id => @calendar.id, :id => exercise.id) %>
	    </div>
		<p><%= exercise.body %></p>
		<p>
			<% if exercise.url.start_with?("https://www.youtube.com/") %>
				<iframe width="560" height="315" src="https://www.youtube.com/embed/<%= exercise.url.split('v=')[-1] %>" frameborder="0" allowfullscreen></iframe>
			<% elsif exercise.url.end_with?(".jpg", ".jpeg", ".png", ".gif") %>
				<img src="<%= exercise.url %>" alt="pic" />
			<% else %>
				<%= exercise.url %>
			<% end %>
		</p>
	</div>
<% end %>

<h2>Add new exercise</h2>

<%= render 'addexercise' %>

<%= link_to "Back", {:action => 'index', :month => @calendar.date.month, :year => @calendar.date.year} %>

app/views/exercises/_logout.html.erb
<%= button_to "Log out", {:action => 'logout', :controller => 'welcome'}, {:class => 'logout-button'} %>

app/views/exercises/edit.html.erb
<%= render partial: 'logout' %>

<h2>Edit exercise</h2>

<div class="addexercise">
	<%= form_for([@calendar, @exercise]) do |f| %>
		<div class="form_row">
				<div class="label"><%= f.label :title %></div>
				<%= f.text_field :title %>
			</div>
			<div class="form_row">
				<div class="label"><%= f.label :body %></div>
				<%= f.text_area :body %>
			</div>
			<div class="form_row">
				<div class="label"><%= f.label :url %></div>
				<%= f.text_field :url %>
			</div>
			
			<div class="form_row">
				<%= f.submit 'Edit exercise', :class => 'button' %>
			</div>
	<% end %>
</div>

<%= link_to "Back", @calendar %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coaching</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
  <% if @user.errors.any? %>
    <div class="register-notice">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being registered:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="register">
  <h1>Register</h1>

  <hr />


  <%= form_for @user do |f| %>
    <div class="form_row">
      <div class="label"><%= f.label :username %></div>
      <%= f.text_field :username %>
    </div>

    <div class="form_row">
      <div class="label"><%= f.label :password %></div>
      <%= f.password_field :password %>
    </div>

    <div class="form_row">
      <div class="label"><%= f.label :repeat %></div>
      <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit :Signup, :class=>'button' %>
  <% end %>

  <hr />

  <div class="bottom_link"><%= link_to 'Back', root_path %></div>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/welcome/login.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<% @page_title = "UserAuth | Login" -%>
<div class= "signin">
  <h1>Log in</h1>
  <hr />
  <%= form_tag(:action => 'login_attempt') do %>
    <div class="form_row"><div class="label">Username</div><%= text_field_tag(:username) %></div>
    <div class="form_row"><div class="label">Password</div><%= password_field_tag :login_password %></div>
    <%= submit_tag("Log In", :class=>"button") %>
  <% end %>

  <hr />
  <div class="bottom_link"><%= link_to 'Register', new_user_path %></div>
</div>